export const data = [
  {
    id: 1,
    abbvTitle: "Mon",
    fullTitle: "Monday",
    events: [],
    active: true,
  },
  {
    id: 2,
    abbvTitle: "Tue",
    fullTitle: "Tuesday",
    events: [],
    active: false,
  },
  {
    id: 3,
    abbvTitle: "Wed",
    fullTitle: "Wednesday",
    events: [],
    active: false,
  },
  {
    id: 4,
    abbvTitle: "Thu",
    fullTitle: "Thursday",
    events: [],
    active: false,
  },
  {
    id: 5,
    abbvTitle: "Fri",
    fullTitle: "Friday",
    events: [],
    active: false,
  },
  {
    id: 6,
    abbvTitle: "Sat",
    fullTitle: "Saturday",
    events: [],
    active: false,
  },
  {
    id: 7,
    abbvTitle: "Sun",
    fullTitle: "Sunday",
    events: [],
    active: false,
  },
];
